#!/bin/bash
# Filename ren_ext ( cht 13-Dec-2005 )
# Purpose : Rename all indicated files in current directory,
# replacing the file extension .old with .new
#
# Usage:
# change-extension old new file [ file ... ]
# where old and new are any names used as filename extensions
# Effect:
# Each <something>.old in the list of files is renamed to <something>.new
# Caution:
# Any file <something> (without extension .old) in the list of files
# is renamed to <something>.new
#----------------------------------------------------------------------------
# Example: In the current directory there are files
# fic.test, mic.test, ficfic ( and no other *.test ).
# running
# ren_ext test tzt *.test ficfic
# will rename those 3 files to
# fic.tzt, mic.tzt, ficfic.tzt

if [ $# -lt 3 ] ; then
echo "Usage:"
echo " $0 old new file [ file ... ]"
exit 1
fi

old=$1; shift
new=$1; shift

while [ $# -gt 0 ] ; do
item=$1; shift
# echo "item: $item"
mv $item ${item%.$old}.$new
done
exit 0