#!/usr/bin/env ruby -w

# Updates Textmate bundles using the Github repositories

# Original version found on http://blog.bleything.net/pages/mateup

ENV['LC_ALL']   = nil
ENV['LC_CTYPE'] = 'en_US.UTF-8'

github_root = 'git://github.com'
bundles = {
  'Ack' => 'protocool/ack-tmbundle',
  'Ant' => 'textmate/ant.tmbundle',
  'Copy as RTF' => 'drnic/copy-as-rtf-tmbundle',
  'Git' => 'jcf/git-tmbundle',
  'Make' => 'textmate/make.tmbundle',
  'Markdown' => 'fletcher/markdown.tmbundle',
  'Maven' => 'textmate/maven.tmbundle',
  'Mediawiki' => 'textmate/mediawiki.tmbundle',
  'Regexp' => 'danielvlopes/regexp-tmbundle',
  'Textile' => 'textmate/textile.tmbundle',
  'TODO' => 'textmate/todo.tmbundle'
}

# escape spaces and ampersands
def cleanup(str)
  return str.gsub(/([ &])/, '\\\\\1')
end

dir = "#{ENV['HOME']}/Library/Application\ Support/TextMate/Bundles"
begin
  Dir.chdir dir
rescue Errno::ENOENT
  puts "Bundles directory doesn't exist... creating it!"
  puts
  
  `mkdir -p '#{dir}'`
  retry
end

Dir.entries('.').each do |e|
  next if e =~ /^\./
  next unless File.directory? e
  
  bundle_name = e.gsub(/.tmbundle$/, '')

  print "* #{bundle_name}: "

  if bundles.delete bundle_name
    puts "bundle exists, updating"
    `cd #{cleanup e}; git pull origin master; cd ..;`
    
  else
    print "don't know about this bundle.  Delete it? [y/N] "

    while answer = gets
      if answer =~ /^y/
        `rm -rf #{cleanup e}`
        puts "  * deleted"
        break
      elsif answer =~ /^(n|$)/
        break
      else
        print "Please enter 'y' or 'n': "
      end
    end
  end
end

bundles.each do |name, source|
  puts "* #{name} doesn't exist; fetching..."
  cmd = "git clone #{github_root}/#{source} #{cleanup name}.tmbundle"
  `#{cmd}`.match(/(revision \d+)/)
  puts "  * checked out #{$1}"
end

`arch -i386 osascript -e 'tell app "TextMate" to reload bundles'`