#!/usr/bin/env ruby
# Original version for Textmate found on
# http://blog.bleything.net/pages/mateup

# Updates Sublime 2/3 packages using their respective Github repositories

# Manage your packages in
# touch ~/.sublime.packages
# For each package create a new line like this
# Git => kemayo/sublime-text-2-git#python3
#
# Use ' => ' as a separator between package name and github repository
# Use '#branch' to pull from a specific branch


ENV['LC_ALL']   = nil
ENV['LC_CTYPE'] = 'en_US.UTF-8'

github_root = 'git://github.com'

packages = Hash[
  File.read(ENV['HOME']+'/.sublime.packages')
  .split("\n").map{|i|i.split(' => ')}
]

print(packages)

# packages provided by default installation
providedPackages = [
  'ActionScript',
  'AppleScript',
  'ASP',#
  'Batch File',
  'C#',
  'C++',
  'Clojure',
  'Color Scheme - Default',
  'CSS',
  'D',
  'Default',
  'Diff',
  'Erlang',
  'Go',
  'Graphviz',
  'Groovy',
  'Haskell',
  'HTML',
  'Java',
  'JavaScript',
  'Language - English',
  'LaTeX',
  'Lisp',
  'Lua',
  'Makefile',
  'Markdown',
  'Matlab',
  'Objective-C',
  'OCaml',
  'Pascal',
  'Python',
  'Perl',
  'PHP',
  'R',
  'Rails',
  'Regular Expressions',
  'RestructuredText',
  'Ruby',
  'Scala',
  'ShellScript',
  'SQL',
  'TCL',
  'Text',
  'Textile',
  'Theme - Default',
  'User',
  'Vintage',
  'XML',
  'YAML'
]

# escape spaces and ampersands
def cleanup(str)
  return str.gsub(/([ &])/, '\\\\\1')
end


def branch(source)
  if (source.nil? || source.split(/#/).length != 2)
    return "master"
  end

  return source.split(/#/)[1]
end

def packageDir()
  if RUBY_PLATFORM.downcase.include?("darwin")
    return "#{ENV['HOME']}/Library/Application\ Support/Sublime\ Text\ 3/Packages"
  elsif RUBY_PLATFORM.downcase.include?("linux")
    return "#{ENV['HOME']}/.config/sublime-text-2/Packages"
  end

  return ""
end

dir = packageDir()
begin
  Dir.chdir dir
rescue Errno::ENOENT
  puts "Packages directory doesn't exist... creating it!"
  puts

  `mkdir -p '#{dir}'`
  retry
end

Dir.entries('.').each do |e|
  next if e =~ /^\./
  next unless File.directory? e

  package_name = e.gsub(/.tmbundle$/, '')
  source = packages[package_name]
  b = branch(source)
  print "* #{package_name} #{source}: "

  if packages.delete package_name
    puts "package exists, updating"
    `cd #{cleanup e}; git pull; git checkout #{b} &> /dev/null; cd ..;`

  else
    if providedPackages.index(package_name)
      print "Ignoring provided package\n"
    else
      print "don't know about this package.  Delete it? [y/n] "

      while answer = gets
        if answer =~ /^y/
          `rm -rf #{cleanup e}`
          puts "  * deleted"
          break
        elsif answer =~ /^(n|$)/
          break
        else
          print "Please enter 'y' or 'n': "
        end
      end
    end
  end
end

packages.each do |name, source|
  puts "* #{name} doesn't exist; fetching..."
  cmd = "git clone #{github_root}/#{source} #{cleanup name}"
  `#{cmd}`.match(/(revision \d+)/)
  puts "  * checked out #{$1}"
  b = branch(source)
  if b != "master"
    `cd #{cleanup e}; git checkout #{b} &> /dev/null; cd ..;`
    puts "  * checked out #{b}"
  end
end
