#! /bin/sh

# prefix to the svn repository
repo=$1

# name of the final project
project=$2

# use local instead of global svn authorsfile
authorsfile=~/.git-svn.authorsfile

rm -rf tmp-$project
mkdir tmp-$project
cd tmp-$project

echo $repo

git svn init $repo --no-metadata
git config svn.authorsfile $authorsfile
git svn fetch


cd ..
git clone tmp-$project $project

rm -rf $project-tmp
 